name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Release Apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          echo $ENCODED_STRING | base64 -di > "${RUNNER_TEMP}"/keystore.jks
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Assemble Release
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      - name: Upload Apk
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/release

  release:
    name: Release Apk
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download apk from build
        uses: actions/download-artifact@v4
        with:
          name: apk
          path: apk
      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          files: apk/app-release.apk
